# Generated by Django 2.2.5 on 2019-12-17 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibbo', '0011_auto_20191127_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 18, 43, 58, 266657)),
        ),
    ]
